name: Default Branch Migration
on: [push]

jobs:
  migrate_branch:
    name: Sync Branch
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: liyanchang/default-branch-migration@v1.0.1
        with:
          # GitHub will fill in this template with the correct token
          # You don't need to edit this line
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # TODO: Change this to the default branch you want to migrate away from
          # The branch to sync changes from
          previous_default: next
          # The branch to sync changes to
          new_default: master
